name: open_resto
description: Restaurant Mobile App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  iconify_flutter: ^0.0.4
  google_fonts: ^3.0.1
  get: ^4.6.5
  http: ^0.13.5
  debounce_builder: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: RedHatDisplay
      fonts:
        - asset: assets/fonts/RedHatDisplay-Bold.ttf
        - asset: assets/fonts/RedHatDisplay-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/RedHatDisplay-Regular.ttf
        - asset: assets/fonts/RedHatDisplay-Italic.ttf
          style: italic
        - asset: assets/fonts/RedHatDisplay-SemiBold.ttf
        - asset: assets/fonts/RedHatDisplay-SemiBoldItalic.ttf
          style: italic
        - asset: assets/fonts/RedHatDisplay-Light.ttf
        - asset: assets/fonts/RedHatDisplay-LightItalic.ttf
          style: italic
        - asset: assets/fonts/RedHatDisplay-Medium.ttf
        - asset: assets/fonts/RedHatDisplay-MediumItalic.ttf
          style: italic
  assets:
    - assets/
    - assets/icons/
    - assets/json/
